version: "3"
networks:
  ryd-coding-challenge-network:
services:
  express-server:
    networks:
      - ryd-coding-challenge-network
    build: .
    environment:
      PORT: 7080
      MONGO_URI: mongodb://mongo:27017/
    ports:
      - 7080:7080
    links:
      - mongo
  mongo:
    networks:
      - ryd-coding-challenge-network
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017